(()=>{
 const $=id=>document.getElementById(id);
 let running=false,sessionId=null,currentTaskId=null,pollTimer=null,lastLogCount=0;
 const inputs=()=>[$('builderPrompt'),$('chatInput'),$('buildInput')].filter(Boolean);
 const buttons=()=>[$('builderSendBtn'),$('sendBtn'),$('buildSendBtn'),$('buildSend')].filter(Boolean);
 function workspace(){return $('panel-build')||$('buildWorkspace')||null}
 function showWorkspace(text){const w=workspace();if(!w)return;if(w.id==='panel-build'){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));w.classList.add('active')}else w.classList.add('active');$('panel-builder')?.classList.add('building');if($('workspaceName'))$('workspaceName').textContent='Build';if($('buildTitle'))$('buildTitle').textContent=text.length>70?text.slice(0,70)+'…':text;if($('buildStatus'))$('buildStatus').textContent='● starting';if($('buildProgress'))$('buildProgress').textContent='Planning';if($('buildChatStatus'))$('buildChatStatus').textContent='working';if($('buildMessages'))$('buildMessages').innerHTML='';if($('previewStatus'))$('previewStatus').textContent='Waiting for runtime…';if($('previewFrame'))$('previewFrame').innerHTML='<div class="preview-empty" id="previewEmpty"><b>Building your project…</b><span>The agent is planning, editing files and running validation.</span></div>');return w}
 function activity(){return $('buildActivity')||(()=>{const x=document.createElement('div');x.id='buildActivity';x.className='chat-activity';$('buildMessages')?.appendChild(x);return x})()}
 function addStep(kind,title,detail='',state='running'){const row=document.createElement('div');row.className=`agent-step ${state}`;row.dataset.kind=kind;row.innerHTML=`<span class="agent-step-dot"></span><div><b>${title}</b>${detail?`<small>${detail}</small>`:''}</div><span class="agent-step-state">${state==='done'?'✓':state==='error'?'!':'…'}</span>`;activity().appendChild(row);activity().scrollTop=activity().scrollHeight;return row}
 function finishStep(row,state,detail){if(!row)return;row.className=`agent-step ${state}`;const mark=row.querySelector('.agent-step-state');if(mark)mark.textContent=state==='done'?'✓':state==='error'?'!':'…';if(detail){let s=row.querySelector('small');if(!s){s=document.createElement('small');row.querySelector('div').appendChild(s)}s.textContent=detail}}
 function mirror(role,text){if(!text)return;[$('builderMessages'),$('buildMessages')].forEach(bm=>{if(!bm)return;const row=document.createElement('div');row.className=`msg-row ${role}`;const av=document.createElement('div');av.className='avatar';av.textContent=role==='user'?'U':'V';const b=document.createElement('div');b.className=`bubble ${role}`;b.textContent=text;row.append(av,b);bm.appendChild(row);bm.scrollTop=bm.scrollHeight})}
 function setPreview(url){if(!url)return;try{const parsed=new URL(String(url),window.location.origin);if(parsed.protocol!=='https:'&&parsed.protocol!=='http:')throw new Error('Unsupported preview protocol');const frame=$('previewFrame');if(frame)frame.innerHTML=`<iframe title="Velclaw live preview" src="${parsed.href.replace(/"/g,'&quot;')}" loading="eager" referrerpolicy="no-referrer"></iframe>`;if($('previewStatus'))$('previewStatus').textContent='Live preview'}catch(e){if($('previewStatus'))$('previewStatus').textContent='Preview unavailable';mirror('agent',`Preview URL rejected: ${e.message}`)}}
 function logEvent(log){const msg=String(log?.message||'').trim();if(!msg)return;const type=log?.type||'info',lower=msg.toLowerCase();if(type==='command'){addStep('tool','Running command',msg);return}if(type==='error'||lower.includes('failed')||lower.includes('error')){addStep('fix','Fixing error',msg,'error');return}if(lower.includes('clone')||lower.includes('inspect')){addStep('inspect','Inspecting workspace',msg);return}if(lower.includes('install')){addStep('setup','Installing dependencies',msg);return}if(lower.includes('test')||lower.includes('validation')){addStep('test','Testing changes',msg);return}if(lower.includes('review')){addStep('review','Reviewing changes',msg);return}if(lower.includes('development server')||lower.includes('preview')){addStep('preview','Preview updated',msg);return}if(type==='success'){addStep('done','Completed',msg,'done');return}mirror('agent',msg)}
 function applyTask(task){if(!task)return;currentTaskId=task.id;const status=task.status||'processing';if($('buildStatus'))$('buildStatus').textContent=`● ${status}`;if($('buildProgress'))$('buildProgress').textContent=`${task.progress??0}%`;const logs=task.logs||[];for(let i=lastLogCount;i<logs.length;i++)logEvent(logs[i]);lastLogCount=logs.length;if(task.previewUrl||task.sandboxUrl)setPreview(task.previewUrl||task.sandboxUrl);if(status==='completed'){stopPolling();running=false;[...activity().querySelectorAll('.agent-step.running')].forEach(s=>finishStep(s,'done'));if($('buildChatStatus'))$('buildChatStatus').textContent='complete';mirror('agent','Build completed. Preview is ready.');enableButtons()}else if(status==='error'||status==='stopped'){stopPolling();running=false;[...activity().querySelectorAll('.agent-step.running')].forEach(s=>finishStep(s,'error',task.error||'Build stopped'));if($('buildChatStatus'))$('buildChatStatus').textContent=status;mirror('agent',status==='stopped'?'Build stopped.':`Build failed: ${task.error||'Unknown error'}`);enableButtons()}}
 async function pollTask(){if(!currentTaskId)return;try{const r=await fetch(`/api/agent/run?taskId=${encodeURIComponent(currentTaskId)}`,{headers:{accept:'application/json'}});const raw=await r.text();let j;try{j=JSON.parse(raw)}catch{j=null}if(!r.ok)throw new Error(j?.error||raw||`HTTP ${r.status}`);applyTask(j.task||j.data?.task)}catch(e){if($('buildStatus'))$('buildStatus').textContent='● connection error';mirror('agent',`Runtime status error: ${e.message}`);stopPolling();running=false;enableButtons()}}
 function startPolling(){stopPolling();pollTimer=setInterval(pollTask,1100);void pollTask()}
 function stopPolling(){if(pollTimer){clearInterval(pollTimer);pollTimer=null}}
 function enableButtons(){buttons().forEach(b=>b.disabled=false)}
 async function run(text){if(!text||running)return;running=true;sessionId=sessionId||crypto.randomUUID();currentTaskId=null;lastLogCount=0;showWorkspace(text);inputs().forEach(i=>{if(i.id==='builderPrompt'||i.id==='chatInput')i.value=''});buttons().forEach(b=>b.disabled=true);mirror('user',text);addStep('plan','Planning','Inspecting requirements and workspace');try{const r=await fetch('/api/agent/run',{method:'POST',headers:{'content-type':'application/json','accept':'application/json, text/event-stream'},body:JSON.stringify({message:text,repoUrl:window.REPO_URL||window.DATA?.dashboard?.repoUrl||undefined,path:window.activePath||null,model:window.DATA?.dashboard?.models?.[0]||null,sessionId,mode:'build',workflow:['plan','inspect','edit','run','test','fix','review','preview']})});const raw=await r.text();let j;try{j=JSON.parse(raw)}catch{j=null}if(!r.ok)throw new Error(j?.error||raw||`HTTP ${r.status}`);const d=j?.data||j;if(d?.taskId){currentTaskId=d.taskId;startPolling();return}if((r.headers.get('content-type')||'').includes('text/event-stream')){for(const chunk of raw.split(/\n\n/)){const line=chunk.split('\n').find(x=>x.startsWith('data:'));if(line)try{parseEvent(JSON.parse(line.slice(5).trim()))}catch{}}}else{for(const e of d?.events||[])parseEvent(e);const answer=d?.response||d?.message||d?.output||d?.assistant?.text;if(answer)mirror('agent',answer);running=false;enableButtons()}}catch(e){[...activity().querySelectorAll('.agent-step.running')].forEach(s=>finishStep(s,'error',e.message));if($('buildStatus'))$('buildStatus').textContent='● error';mirror('agent',`Build error: ${e.message}`);running=false;enableButtons()}}
 function parseEvent(ev){if(!ev)return;const type=ev.type||ev.event||ev.kind||'message',data=ev.data??ev;if(type==='tool_call'||type==='tool'||type==='command')addStep('tool',data.name||data.tool||'run_command',data.command||data.input||'','running');else if(type==='tool_result'||type==='command_result')finishStep([...activity().querySelectorAll('.agent-step.running')].at(-1),'done',String(data.output||data.result||'Completed').slice(0,180));else if(type==='file_write'||type==='file_edit'||type==='edit'||type==='patch')addStep('edit','Editing code',data.path||data.file||'workspace','running');else if(type==='runtime'||type==='run'){addStep('run','Running project',data.command||data.url||'runtime','running');if(data.url)setPreview(data.url)}else if(type==='test'||type==='ci')addStep('test','Testing changes',data.command||data.status||'validation','running');else if(type==='preview'){addStep('preview','Preview updated',data.url||'live preview','running');if(data.url)setPreview(data.url)}else if(type==='reasoning'||type==='thinking')addStep('think','Working',data.text||data.message||'Analyzing next action','running');else if(type==='done'||type==='complete'){[...activity().querySelectorAll('.agent-step.running')].forEach(s=>finishStep(s,'done'));running=false}else if(type==='error'){[...activity().querySelectorAll('.agent-step.running')].forEach(s=>finishStep(s,'error',data.message||data.error||'Agent error'));running=false}else{const text=data.text||data.message||data.response||data.output;if(text)mirror('agent',text)}}
 async function sendFollowup(text){if(!text||!currentTaskId||running)return;running=true;mirror('user',text);addStep('plan','Continuing build','Applying the follow-up request to the existing workspace');try{const r=await fetch('/api/agent/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:text,taskId:currentTaskId,repoUrl:window.REPO_URL||window.DATA?.dashboard?.repoUrl,model:window.DATA?.dashboard?.models?.[0],mode:'build',action:'followup'})});const raw=await r.text();let j;try{j=JSON.parse(raw)}catch{j=null}if(!r.ok)throw new Error(j?.error||raw||`HTTP ${r.status}`);const d=j?.data||j;if(d?.taskId){currentTaskId=d.taskId;startPolling();return}throw new Error('Runtime did not return a task id')}catch(e){mirror('agent',`Follow-up failed: ${e.message}`);running=false;enableButtons()}}
 function boot(){const bp=$('builderPrompt'),bs=$('builderSendBtn'),ci=$('chatInput'),cs=$('sendBtn'),bi=$('buildInput'),bss=$('buildSendBtn')||$('buildSend');if(bp&&bs){bs.disabled=!bp.value.trim();bp.oninput=()=>bs.disabled=!bp.value.trim();bp.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();run(bp.value.trim())}};bs.onclick=()=>run(bp.value.trim())}if(ci&&cs){cs.disabled=!ci.value.trim();ci.oninput=()=>cs.disabled=!ci.value.trim();ci.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();run(ci.value.trim())}};cs.onclick=()=>run(ci.value.trim())}if(bi&&bss){bss.disabled=false;bi.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendFollowup(bi.value.trim())}};bss.onclick=()=>sendFollowup(bi.value.trim())}$('backToBuilder')?.addEventListener('click',()=>{stopPolling();running=false;document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));$('panel-builder')?.classList.add('active');if($('workspaceName'))$('workspaceName').textContent='AI Builder'});$('stopBuildBtn')?.addEventListener('click',stopBuild)}
 async function stopBuild(){if(!currentTaskId)return;try{const r=await fetch(`/api/agent/run?taskId=${encodeURIComponent(currentTaskId)}&action=stop`,{method:'DELETE',headers:{accept:'application/json'}});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.error||`HTTP ${r.status}`)}}catch(e){mirror('agent',`Stop failed: ${e.message}`)}stopPolling();running=false;enableButtons()}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();