(()=>{
 const $=id=>document.getElementById(id);
 let running=false,sessionId=null;
 function activity(){return $('chatActivity')||(()=>{const x=document.createElement('div');x.id='chatActivity';x.className='chat-activity';const m=$('chatMessages');m?.parentElement?.insertBefore(x,m);return x})()}
 function addStep(kind,title,detail='',state='running'){const row=document.createElement('div');row.className=`agent-step ${state}`;row.innerHTML=`<span class="agent-step-dot"></span><div><b>${title}</b>${detail?`<small>${detail}</small>`:''}</div><span class="agent-step-state">${state==='done'?'✓':state==='error'?'!':'…'}</span>`;activity().appendChild(row);activity().scrollTop=activity().scrollHeight;return row}
 function finishStep(row,state,detail){if(!row)return;row.className=`agent-step ${state}`;row.querySelector('.agent-step-state').textContent=state==='done'?'✓':state==='error'?'!':'…';if(detail){let s=row.querySelector('small');if(!s){s=document.createElement('small');row.querySelector('div').appendChild(s)}s.textContent=detail}}
 function message(role,text){if(window.appendMessage)window.appendMessage(role,text)}
 function parseEvent(ev){if(!ev)return;let type=ev.type||ev.event||ev.kind||'message';let data=ev.data??ev;try{if(typeof data==='string')data=JSON.parse(data)}catch{};if(type==='tool_call'||type==='tool'||type==='command'){const name=data.name||data.tool||data.command||'tool';const detail=data.command||data.input||data.args||'';addStep('tool',name,typeof detail==='string'?detail:JSON.stringify(detail));return}if(type==='tool_result'||type==='command_result'){const steps=[...activity().querySelectorAll('.agent-step')];finishStep(steps.at(-1),'done',String(data.output||data.result||'Completed').slice(0,180));return}if(type==='file_write'||type==='edit'||type==='patch'){addStep('edit','Updating code',data.path||data.file||'workspace');return}if(type==='runtime'||type==='run'){addStep('run','Starting runtime',data.command||data.url||'workspace');return}if(type==='test'||type==='ci'){addStep('test','Running tests',data.command||data.status||'validation');return}if(type==='preview'){addStep('preview','Preview ready',data.url||'local preview');return}if(type==='done'||type==='complete'){const steps=[...activity().querySelectorAll('.agent-step')];finishStep(steps.at(-1),'done');running=false;return}if(type==='error'){const steps=[...activity().querySelectorAll('.agent-step')];finishStep(steps.at(-1),'error',data.message||data.error||'Agent error');running=false;return}const text=data.text||data.message||data.response||data.output;if(text)message('agent',text)}
 async function run(text){if(running)return;running=true;sessionId=sessionId||crypto.randomUUID();message('user',text);const old=$('chatInput');if(old){old.value='';$('sendBtn').disabled=true}activity().innerHTML='';addStep('plan','Planning build','Inspecting workspace and requirements');try{const r=await fetch('/api/agent/run',{method:'POST',headers:{'content-type':'application/json','accept':'text/event-stream, application/json'},body:JSON.stringify({message:text,path:window.activePath||null,model:window.DATA?.dashboard?.models?.[0]||null,sessionId,mode:'build'})});if(!r.ok)throw new Error((await r.text())||`HTTP ${r.status}`);const ct=r.headers.get('content-type')||'';if(ct.includes('text/event-stream')&&r.body){const reader=r.body.getReader(),dec=new TextDecoder();let buf='';while(true){const {done,value}=await reader.read();if(done)break;buf+=dec.decode(value,{stream:true});const parts=buf.split(/\n\n/);buf=parts.pop()||'';for(const p of parts){const line=p.split('\n').find(x=>x.startsWith('data:'));if(line){try{parseEvent(JSON.parse(line.slice(5).trim()))}catch{}}}}}else{const j=await r.json();const d=j.data||j;for(const e of d.events||[])parseEvent(e);const answer=d.response||d.message||d.output||d.assistant?.text;if(answer)message('agent',answer)}const steps=[...activity().querySelectorAll('.agent-step')];steps.forEach(s=>{if(s.classList.contains('running'))finishStep(s,'done')});}catch(e){addStep('error','Build failed',e.message,'error');message('agent',`Build error: ${e.message}`)}finally{running=false;if($('sendBtn'))$('sendBtn').disabled=!($('chatInput')?.value.trim())}}
 function boot(){const input=$('chatInput'),btn=$('sendBtn');if(!input||!btn)return;btn.onclick=()=>run(input.value.trim());input.oninput=()=>btn.disabled=!input.value.trim()}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
