let DATA=null,activePath=null,dirty=false,wrap=false,openTabs=[];
const $=id=>document.getElementById(id);
const ICON={file:'<svg viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/></svg>',dir:'<svg viewBox="0 0 24 24"><path d="M3 6a2 2 0 0 1 2-2h5l2 2h7a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z"/></svg>',bot:'◌'};
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
async function init(){
 try{DATA=await api('data.json')}catch{DATA={fileTree:[],fileContents:{},chat:{initialMessages:[]},dashboard:{models:[]}}}
 setupMenu();setupTabs();setupTree();setupEditor();setupChat();setupCommands();setupDashboard();await refreshTree();await refreshStatus();
}
function setupMenu(){
 const open=()=>{$('menuOverlay').classList.add('open');$('menuOverlay').setAttribute('aria-hidden','false')};const close=()=>{$('menuOverlay').classList.remove('open');$('menuOverlay').setAttribute('aria-hidden','true')};
 $('openMenuBtn').onclick=open;$('closeMenuBtn').onclick=close;$('menuBackdrop').onclick=close;
 document.querySelectorAll('.menu-item[data-tab]').forEach(b=>b.onclick=()=>{switchTab(b.dataset.tab);close()});
 $('chatQuickBtn').onclick=()=>switchTab('chat');$('reloadMenuBtn').onclick=async()=>{close();await refreshTree();await refreshStatus()};
}
function setupTabs(){}
function switchTab(tab){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));const panel=$(`panel-${tab}`);if(panel)panel.classList.add('active');document.querySelectorAll('.menu-item[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));}
function setupTree(){
 const open=()=>{$('treeOverlay').classList.add('open');$('treeOverlay').setAttribute('aria-hidden','false')};const close=()=>{$('treeOverlay').classList.remove('open');$('treeOverlay').setAttribute('aria-hidden','true')};
 $('openTreeBtn').onclick=open;$('closeTreeBtn').onclick=close;$('treeBackdrop').onclick=close;$('refreshTreeBtn').onclick=refreshTree;$('fileFilter').oninput=()=>renderTree(filterTree(DATA?.fileTree||[],$('fileFilter').value.toLowerCase()),$('fileTree'),0);
}
function filterTree(nodes,q){if(!q)return nodes;return nodes.flatMap(n=>{if(n.type==='file')return n.name.toLowerCase().includes(q)?[n]:[];const children=filterTree(n.children||[],q);return children.length||n.name.toLowerCase().includes(q)?[{...n,children}]:[]})}
async function refreshTree(){try{const r=await api('/api/workspace/tree');DATA.fileTree=r.tree||[];renderTree(DATA.fileTree,$('fileTree'),0)}catch{renderTree(DATA?.fileTree||[],$('fileTree'),0)}}
function renderTree(nodes,container,depth){container.innerHTML='';nodes.forEach(node=>{const li=document.createElement('li');if(node.type==='dir'){const b=document.createElement('button');b.style.paddingLeft=`${7+depth*14}px`;b.innerHTML=`${ICON.dir}<span class="name">${esc(node.name)}</span><span style="margin-left:auto">›</span>`;let child; b.onclick=()=>{if(child)child.hidden=!child.hidden};li.appendChild(b);child=document.createElement('ul');renderTree(node.children||[],child,depth+1);li.appendChild(child)}else{const b=document.createElement('button');b.className='tree-file';b.dataset.path=node.path;b.style.paddingLeft=`${7+depth*14}px`;b.innerHTML=`${ICON.file}<span class="name">${esc(node.name)}</span>`;b.onclick=()=>{selectFile(node.path);$('treeOverlay').classList.remove('open')};li.appendChild(b)}container.appendChild(li)})}
function setupEditor(){
 $('saveBtn').onclick=saveFile;$('wrapBtn').onclick=()=>{wrap=!wrap;$('editorWrap').classList.toggle('wrap',wrap)};$('searchBtn').onclick=()=>{const q=prompt('Tìm trong file đang mở');if(q){const i=$('codeArea').value.indexOf(q);if(i>=0){$('codeArea').focus();$('codeArea').setSelectionRange(i,i+q.length)}}};
 $('codeArea').addEventListener('input',()=>{dirty=true;$('saveBtn').disabled=false;updateEditorMeta();renderGutter()});$('codeArea').addEventListener('scroll',()=>{$('gutter').scrollTop=$('codeArea').scrollTop});$('codeArea').addEventListener('click',updateCursor);$('codeArea').addEventListener('keyup',updateCursor);$('codeArea').addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();const s=e.target.selectionStart;e.target.value=e.target.value.slice(0,s)+'  '+e.target.value.slice(e.target.selectionEnd);e.target.selectionStart=e.target.selectionEnd=s+2;dirty=true;$('saveBtn').disabled=false;renderGutter()}})}
async function selectFile(path){if(dirty&&!confirm('File chưa lưu. Bỏ thay đổi?'))return;activePath=path;dirty=false;$('saveBtn').disabled=true;$('editorOverlay').classList.add('show');$('breadcrumbFile').textContent=path;$('codeArea').value='';try{const r=await api(`/api/workspace/file?path=${encodeURIComponent(path)}`);$('codeArea').value=r.content}catch(e){$('codeArea').value=DATA?.fileContents?.[path]||`// Không đọc được ${path}\n// ${e.message}`}$('editorOverlay').classList.remove('show');if(!openTabs.includes(path))openTabs.push(path);renderTabs();document.querySelectorAll('.tree-file').forEach(b=>b.classList.toggle('active',b.dataset.path===path));updateEditorMeta();renderGutter()}
function renderTabs(){const el=$('editorTabs');el.innerHTML='';openTabs.forEach(p=>{const t=document.createElement('button');t.className='tab'+(p===activePath?' active':'');t.innerHTML=`${esc(p.split('/').pop())}${p===activePath&&dirty?'<span>•</span>':''}<span class="tab-close">×</span>`;t.onclick=e=>{if(e.target.classList.contains('tab-close')){openTabs=openTabs.filter(x=>x!==p);if(activePath===p&&openTabs.length)selectFile(openTabs[openTabs.length-1]);renderTabs()}else selectFile(p)};el.appendChild(t)})}
async function saveFile(){if(!activePath)return;const b=$('saveBtn');b.disabled=true;b.textContent='Saving…';try{await api('/api/workspace/file',{method:'POST',body:JSON.stringify({path:activePath,content:$('codeArea').value})});dirty=false;$('editorStatus').textContent='Saved';renderTabs()}catch(e){$('editorStatus').textContent=`Save failed: ${e.message}`;dirty=true;b.disabled=false}b.textContent='Lưu';if(!dirty)b.disabled=true}
function renderGutter(){const n=Math.max(1,$('codeArea').value.split('\n').length);$('gutter').innerHTML=Array.from({length:n},(_,i)=>`<div>${i+1}</div>`).join('')}
function updateCursor(){const ta=$('codeArea'),before=ta.value.slice(0,ta.selectionStart),line=before.split('\n').length,col=before.length-(before.lastIndexOf('\n')+1)+1;$('cursorStatus').textContent=`Ln ${line}, Col ${col}`}
function updateEditorMeta(){const p=activePath||'',ext=p.split('.').pop().toLowerCase(),map={js:'JavaScript',ts:'TypeScript',tsx:'TypeScript React',jsx:'JavaScript React',json:'JSON',html:'HTML',css:'CSS',md:'Markdown',py:'Python',yml:'YAML',yaml:'YAML',sh:'Shell'};$('languageStatus').textContent=map[ext]||'Plain Text';$('editorStatus').textContent=dirty?'Modified':'Ready';updateCursor();renderTabs()}
function setupChat(){
 const input=$('chatInput');$('sendBtn').onclick=send;input.oninput=()=>{$('sendBtn').disabled=!input.value.trim()};input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};$('clearChatBtn').onclick=()=>{$('chatMessages').innerHTML=''};(DATA?.chat?.initialMessages||[]).forEach(m=>appendMessage(m.role,m.text))
}
async function send(){const input=$('chatInput'),text=input.value.trim();if(!text)return;appendMessage('user',text);input.value='';$('sendBtn').disabled=true;appendMessage('agent','Velclaw đang xử lý…','typing');try{const r=await api('/api/agent/chat',{method:'POST',body:JSON.stringify({message:text,path:activePath,model:DATA?.dashboard?.models?.[0]})});document.querySelectorAll('.typing').forEach(e=>e.remove());const p=r.data||r,a=p.assistant;const answer=typeof a==='string'?a:a?.text||a?.content||p.response||p.message||p.output||(r.configured===false?'Agent chưa được cấu hình.':JSON.stringify(p,null,2));appendMessage('agent',answer)}catch(e){document.querySelectorAll('.typing').forEach(x=>x.remove());appendMessage('agent',`Lỗi agent: ${e.message}`)} }
function appendMessage(role,text,cls=''){const row=document.createElement('div');row.className=`msg-row ${role} ${cls}`;const av=document.createElement('div');av.className='avatar';av.textContent=role==='user'?'U':ICON.bot;const b=document.createElement('div');b.className=`bubble ${role}`;b.textContent=text;row.append(av,b);$('chatMessages').appendChild(row);$('chatMessages').scrollTop=$('chatMessages').scrollHeight}
function setupDashboard(){$('refreshBtn').onclick=refreshStatus}
async function refreshStatus(){try{const s=await api('/api/workspace/status'),ok=!!s.agent?.configured;$('deployStatus').textContent=ok?'Agent connected':'Workspace online · Agent not configured';$('agentStatus').textContent=ok?'● connected':'● offline';$('agentStatus').style.color=ok?'var(--teal)':'var(--muted)';$('menuBackendStatus').textContent=ok?'Backend connected':'Backend online · agent not configured';$('dashboardContent').innerHTML=`<div class="dash-card"><div class="dash-title">Runtime</div><div class="dash-row"><span>Workspace</span><b>${esc(s.workspace||'local')}</b></div><div class="dash-row"><span>Node</span><b>${esc(s.server?.node||'—')}</b></div><div class="dash-row"><span>Agent</span><b class="${ok?'ok':'muted'}">${ok?'connected':'not configured'}</b></div></div><div class="dash-card"><div class="dash-title">Endpoints</div><div class="dash-row"><span>Workspace API</span><b class="ok">ready</b></div><div class="dash-row"><span>Agent API</span><b class="${ok?'ok':'muted'}">${ok?'ready':'waiting for URL'}</b></div></div>`}catch(e){$('deployStatus').textContent='Backend offline';$('agentStatus').textContent='● offline';$('menuBackendStatus').textContent='Backend offline'}}
function setupCommands(){const open=()=>{$('commandOverlay').classList.add('open');$('commandInput').value='';renderCommands('')};const close=()=>$('commandOverlay').classList.remove('open');$('commandBtn').onclick=open;$('commandMenuBtn').onclick=()=>{document.querySelector('.side-menu')&&$('menuOverlay').classList.remove('open');open()};$('commandBackdrop').onclick=close;$('commandInput').oninput=e=>renderCommands(e.target.value.toLowerCase());document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open()}if(e.key==='Escape'){close();$('menuOverlay').classList.remove('open');$('treeOverlay').classList.remove('open')}})}
function renderCommands(q){const items=[['Open Codebase','files'],['Open Agent','chat'],['Open Source Control','git'],['Open Dashboard','dashboard'],['Open file tree','tree'],['Refresh workspace','refresh']].filter(x=>x[0].toLowerCase().includes(q));$('commandList').innerHTML='';items.forEach(([label,act])=>{const b=document.createElement('div');b.className='command-row';b.innerHTML=`<div><b>${label}</b><small>${act}</small></div>`;b.onclick=()=>{if(act==='tree')$('treeOverlay').classList.add('open');else if(act==='refresh'){refreshTree();refreshStatus()}else switchTab(act);$('commandOverlay').classList.remove('open')};$('commandList').appendChild(b)})}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
init();