let DATA=null,activePath=null,dirty=false,wrap=false,openTabs=[];
const $=id=>document.getElementById(id);
const ICON={file:'<svg viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/></svg>',dir:'<svg viewBox="0 0 24 24"><path d="M3 6a2 2 0 0 1 2-2h5l2 2h7a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z"/></svg>',bot:'◌'};
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
async function init(){try{DATA=await api('data.json')}catch{DATA={fileTree:[],fileContents:{},chat:{initialMessages:[]},dashboard:{models:[]}}}setupMenu();setupTree();setupEditor();setupChat();setupCommands();setupDashboard();setupGit();await refreshTree();await refreshStatus();await refreshGit()}
function setupMenu(){const open=()=>{$('menuOverlay').classList.add('open');$('menuOverlay').setAttribute('aria-hidden','false')},close=()=>{$('menuOverlay').classList.remove('open');$('menuOverlay').setAttribute('aria-hidden','true')};$('openMenuBtn').onclick=open;$('closeMenuBtn').onclick=close;$('menuBackdrop').onclick=close;document.querySelectorAll('.menu-item[data-tab]').forEach(b=>b.onclick=()=>{switchTab(b.dataset.tab);close()});document.querySelectorAll('.menu-item[data-view]').forEach(b=>b.onclick=()=>{openPortal(b.dataset.view);close()});$('chatQuickBtn').onclick=()=>switchTab('chat');$('reloadMenuBtn')?.addEventListener('click',async()=>{close();await refreshTree();await refreshStatus();await refreshGit()})}
function switchTab(tab){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));const panel=$(`panel-${tab}`);if(panel)panel.classList.add('active');document.querySelectorAll('.menu-item[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='git')refreshGit()}
const viewCatalog={
'new-application':['New Application','Create a complete app','Choose a product type, stack, integrations and an agent workflow.',['Web App','Mobile App','Desktop App','API / Backend','AI Agent','Chatbot','MCP Server','CLI']],
'new-project':['New Project','Create a development workspace','Start from scratch or attach an existing repository.',['Blank Project','From GitHub','From Template','Import Workspace']],
'new-agent':['New Agent','Create an autonomous coding agent','Define goals, tools, permissions and execution policy.',['Coding Agent','Review Agent','Test Agent','Deploy Agent','Research Agent']],
'new-plugin':['New Plugin','Create a Velclaw plugin','Package tools, UI, commands and optional MCP capabilities.',['Tool Plugin','UI Plugin','MCP Plugin','Integration Plugin']],
'new-workspace':['New Workspace','Create an isolated workspace','Separate project files, environment settings and agent context.',['Local Workspace','Remote Workspace','Sandbox Workspace']],
'agent-builder':['Agent Builder','Build an agent workflow','Plan → inspect → execute → test → review → fix → gate.',['Plan','Inspect','Execute','Test','Review','Fix','Gate']],
'chat-builder':['Chat Builder','Build an AI chatbot','Configure conversation behavior, tools, memory and UI.',['Chat UI','System Prompt','Tools','Memory','Guardrails']],
'app-builder':['App Builder','Generate application architecture','Compose frontend, backend, data and deployment layers.',['Frontend','Backend','Database','Auth','Deployment']],
'code-generator':['Code Generator','Generate implementation','Generate files from requirements while preserving project conventions.',['Function','Component','API','Test','Migration','Documentation']],
'ui-builder':['UI Builder','Compose interface screens','Build responsive screens from reusable components and design tokens.',['Screen','Navigation','Form','Dashboard','Component']],
'api-builder':['API Builder','Design APIs','Define routes, schemas, authentication and tests.',['REST','GraphQL','Webhook','Auth','OpenAPI']],
'terminal':['Terminal','Runtime and shell','The terminal view is prepared for runtime execution and command streaming.',['Shell','Node.js','Python','Git','Package Manager']],
'my-projects':['My Projects','Project workspaces','Your projects will appear here when workspace persistence is connected.',['Create project','Import repository','Open recent']],
'recent':['Recent','Recently opened','Quick access to recent workspaces and files.',['Workspace','Project','File']],
'templates':['Templates','Starter templates','Ready-to-build project blueprints for common stacks.',['Next.js SaaS','React Dashboard','FastAPI API','AI Chatbot','MCP Server','Mobile App']],
'examples':['Examples','Reference projects','Browse implementation examples for Velclaw workflows.',['Agent','Full-stack','MCP','Dashboard','CI/CD']],
'ui-patterns':['UI Patterns','Interface patterns','Reusable interaction patterns for professional product interfaces.',['Navigation','Command Menu','Editor','Inspector','Dashboard']],
'components':['Components','Reusable components','A component catalog for building consistent application surfaces.',['Buttons','Forms','Tables','Dialogs','Cards','Navigation']],
'design-system':['Design System','Tokens and components','Centralize typography, spacing, colors and reusable components.',['Tokens','Typography','Color','Spacing','Components']],
'languages':['Languages','Language tooling','Runtime and language support detected by the workspace.',['JavaScript','TypeScript','Python','Go','Rust','Java','Swift','C / C++']],
'sdks':['SDKs','Platform SDKs','SDK discovery and configuration for connected services.',['GitHub SDK','Figma SDK','Supabase SDK','Vercel SDK']],
'packages':['Packages','Dependencies','Package discovery, installation and version management.',['npm','pnpm','pip','cargo']],
'libraries':['Libraries','Reusable libraries','Search libraries and add them to a project.',['UI','Auth','Database','AI','Testing']],
'installed-plugins':['Installed','Installed plugins','Manage plugin lifecycle, permissions and configuration.',['Enabled','Disabled','Updates']],
'marketplace':['Marketplace','Plugin marketplace','Discover developer tools and integrations for Velclaw.',['Developer Tools','AI','Design','Productivity']],
'mcp':['MCP Servers','MCP connections','Connect external tools and data sources through MCP.',['Connected','Available','Add Server']],
'add-plugin':['Add Plugin','Install a plugin','Add from marketplace, package or MCP server.',['Marketplace','Package','MCP URL','Local Plugin']],
'github':['GitHub','Repository integration','Use GitHub for source control, issues, pull requests and Actions.',['Repositories','Branches','Pull Requests','Issues','Actions']],
'figma-integration':['Figma','Design integration','Bring design context and Code Connect into the coding workflow.',['Design Context','Components','Variables','Code Connect']],
'supabase':['Supabase','Backend integration','Database, Auth, Storage and server-side project tooling.',['Database','Auth','Storage','Functions']],
'vercel':['Vercel','Deployment integration','Preview, production deployment and runtime diagnostics.',['Projects','Deployments','Logs','Domains']],
'notion':['Notion','Knowledge integration','Project documentation, specs and knowledge.',['Docs','PRD','Knowledge','Tasks']],
'linear':['Linear','Project management integration','Issues, projects and execution tracking.',['Issues','Projects','Cycles','Roadmaps']],
'slack':['Slack','Team integration','Notifications and collaboration from the workspace.',['Channels','Messages','Alerts']],
'sentry':['Sentry','Error monitoring integration','Inspect runtime errors and connect fixes to the agent workflow.',['Issues','Stack Traces','Releases','Performance']],
'posthog':['PostHog','Product analytics integration','Events, feature flags and experiments.',['Events','Flags','Experiments','Insights']],
'documentation':['Documentation','Developer documentation','Central place for language, SDK, API and platform references.',['Platform','Languages','Frameworks','Deployment']],
'apis':['APIs','API catalog','Browse API contracts and connected service endpoints.',['REST','GraphQL','Webhooks','OpenAPI']],
'resource-libraries':['Libraries','Library resources','Discover libraries by language and use case.',['Frontend','Backend','AI','Testing']],
'resource-components':['Components','Component resources','Reference implementations and component systems.',['UI','Forms','Data','Navigation']],
'models':['AI Models','Models and providers','Configure model routing for agents and builders.',['Providers','Models','Routing','Limits']],
'search':['Search','Workspace search','Search files, projects, resources, plugins and integrations.',['Files','Projects','Libraries','Plugins']],
'diagnostics':['Diagnostics','System diagnostics','Inspect backend, runtime, agent and integration health.',['Backend','Agent','GitHub','Runtime','CI']],
'profile':['User Profile','Profile and preferences','Manage identity and personal workspace preferences.',['Profile','Username','Email','Language','Timezone']],
'security':['Security','Tokens, keys and permissions','Manage credentials without exposing secrets in the client.',['API Tokens','SSH Keys','Permissions','Security Log']],
'ai-settings':['AI & Agents','AI configuration','Configure providers, models, prompts, memory and agent permissions.',['AI Providers','Models','System Prompts','Memory','Permissions']],
'integration-settings':['Integrations','Connections and OAuth','Manage third-party connections and authorization state.',['Connected','OAuth','Scopes','Disconnect']],
'plugin-settings':['Plugins','Plugin settings','Manage plugin permissions, sandboxing and MCP access.',['Installed','Permissions','MCP','Sandbox']],
'system':['System Utilities','Runtime and system utilities','Detect and manage available developer runtimes and package tools.',['Node.js','Python','Git','Shell','npm','pnpm','pip','cargo']],
'editor-settings':['Editor','Editor preferences','Configure editor behavior and keybindings.',['Theme','Font','Word Wrap','Keybindings','Accessibility']],
'workspace-settings':['Workspace','Workspace preferences','Configure storage, autosave and workspace permissions.',['Storage','Autosave','Files','Permissions']],
'notifications':['Notifications','Notification settings','Control agent, build, CI and deployment alerts.',['Agent','Build','CI','Deployment','System']],
'advanced':['Advanced','Advanced settings','Logs, diagnostics, experimental features and reset controls.',['Logs','Experimental','Diagnostics','Cache','Reset']]
};
function openPortal(view){const c=viewCatalog[view]||['Velclaw','Developer workspace','Select a capability from the menu.',[]];$('portalTitle').textContent=c[0];$('portalSubtitle').textContent=c[1];$('portalContent').innerHTML=`<div class="portal-hero"><div><span class="eyebrow">VELCLAW</span><h1>${esc(c[0])}</h1><p>${esc(c[2])}</p></div><button class="primary-action" onclick="portalPrimary('${view}')">${view.startsWith('new-')?'Create':view==='security'?'Manage API Tokens':'Open'}</button></div><div class="portal-grid">${c[3].map((x,i)=>`<button class="portal-card" onclick="portalAction('${view}',${i})"><span class="portal-index">${String(i+1).padStart(2,'0')}</span><strong>${esc(x)}</strong><small>${portalHint(view,x)}</small><span class="portal-arrow">→</span></button>`).join('')}</div>`;document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));$('panel-portal').classList.add('active');document.querySelectorAll('.menu-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
function portalHint(view,x){if(view==='security'&&x==='API Tokens')return 'Create and revoke scoped tokens';if(view==='system')return 'Detect availability and configuration';if(view==='mcp')return 'Connect tools and external data';if(view.includes('builder'))return 'Configure this build stage';return 'Open this workspace capability'}
function portalPrimary(view){if(view==='new-application')openPortal('app-builder');else if(view==='security')openPortal('security');else alert(`${viewCatalog[view]?.[0]||'Velclaw'} is ready for configuration.`)}
function portalAction(view,index){const item=viewCatalog[view]?.[3]?.[index]||'item';if(view==='new-application'&&index===5)openPortal('chat-builder');else if(view==='security'&&item==='API Tokens')openTokenPanel();else alert(`${item}: module scaffold is ready. Connect the corresponding backend/plugin to enable live actions.`)}
function openTokenPanel(){const p=$('portalContent');p.innerHTML=`<div class="dash-card token-card"><div class="dash-title">API Tokens <span class="substatus">Secret management</span></div><div class="dash-row"><span>Token name</span><input id="tokenName" placeholder="Production Agent"></div><div class="dash-row"><span>Scope</span><b>agent:run · files:read · files:write</b></div><div class="dash-row"><span>Expiration</span><select id="tokenExpiry"><option>30 days</option><option selected>90 days</option><option>1 year</option></select></div><button class="primary-action" onclick="createTokenUI()">Create Token</button></div><div class="dash-card"><div class="dash-title">Security rule</div><div class="dash-row"><span>Client storage</span><b class="ok">Never store plaintext secrets</b></div><div class="dash-row"><span>Display</span><b class="muted">Show once after creation</b></div></div>`}
function createTokenUI(){const name=$('tokenName')?.value.trim()||'Velclaw Token';const fake=`vclw_${crypto.getRandomValues(new Uint32Array(3)).join('').slice(0,24)}`;alert(`Token created for ${name}.\n\n${fake}\n\nProduction implementation must persist only a hash server-side and show the secret once.`)}
function setupTree(){const open=()=>{$('treeOverlay').classList.add('open');$('treeOverlay').setAttribute('aria-hidden','false')},close=()=>{$('treeOverlay').classList.remove('open');$('treeOverlay').setAttribute('aria-hidden','true')};$('openTreeBtn').onclick=open;$('closeTreeBtn').onclick=close;$('treeBackdrop').onclick=close;$('refreshTreeBtn').onclick=refreshTree;$('fileFilter').oninput=()=>renderTree(filterTree(DATA?.fileTree||[],$('fileFilter').value.toLowerCase()),$('fileTree'),0)}
function filterTree(nodes,q){if(!q)return nodes;return nodes.flatMap(n=>{if(n.type==='file')return n.name.toLowerCase().includes(q)?[n]:[];const children=filterTree(n.children||[],q);return children.length||n.name.toLowerCase().includes(q)?[{...n,children}]:[]})}
async function refreshTree(){try{const r=await api('/api/workspace/tree');DATA.fileTree=r.tree||[];renderTree(DATA.fileTree,$('fileTree'),0)}catch{renderTree(DATA?.fileTree||[],$('fileTree'),0)}}
function renderTree(nodes,container,depth){container.innerHTML='';nodes.forEach(node=>{const li=document.createElement('li');if(node.type==='dir'){const b=document.createElement('button');b.style.paddingLeft=`${7+depth*14}px`;b.innerHTML=`${ICON.dir}<span class="name">${esc(node.name)}</span><span style="margin-left:auto">›</span>`;let child;b.onclick=()=>{if(child)child.hidden=!child.hidden};li.appendChild(b);child=document.createElement('ul');renderTree(node.children||[],child,depth+1);li.appendChild(child)}else{const b=document.createElement('button');b.className='tree-file';b.dataset.path=node.path;b.style.paddingLeft=`${7+depth*14}px`;b.innerHTML=`${ICON.file}<span class="name">${esc(node.name)}</span>`;b.onclick=()=>{selectFile(node.path);$('treeOverlay').classList.remove('open')};li.appendChild(b)}container.appendChild(li)})}
function setupEditor(){$('saveBtn').onclick=saveFile;$('wrapBtn').onclick=()=>{wrap=!wrap;$('editorWrap').classList.toggle('wrap',wrap)};$('searchBtn').onclick=()=>{const q=prompt('Tìm trong file đang mở');if(q){const i=$('codeArea').value.indexOf(q);if(i>=0){$('codeArea').focus();$('codeArea').setSelectionRange(i,i+q.length)}}};$('codeArea').addEventListener('input',()=>{dirty=true;$('saveBtn').disabled=false;updateEditorMeta();renderGutter()});$('codeArea').addEventListener('scroll',()=>{$('gutter').scrollTop=$('codeArea').scrollTop});$('codeArea').addEventListener('click',updateCursor);$('codeArea').addEventListener('keyup',updateCursor);$('codeArea').addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();const s=e.target.selectionStart;e.target.value=e.target.value.slice(0,s)+'  '+e.target.value.slice(e.target.selectionEnd);e.target.selectionStart=e.target.selectionEnd=s+2;dirty=true;$('saveBtn').disabled=false;renderGutter()}})}
async function selectFile(path){if(dirty&&!confirm('File chưa lưu. Bỏ thay đổi?'))return;activePath=path;dirty=false;$('saveBtn').disabled=true;$('editorOverlay').classList.add('show');$('breadcrumbFile').textContent=path;$('codeArea').value='';try{const r=await api(`/api/workspace/file?path=${encodeURIComponent(path)}`);$('codeArea').value=r.content}catch(e){$('codeArea').value=DATA?.fileContents?.[path]||`// Không đọc được ${path}\n// ${e.message}`}$('editorOverlay').classList.remove('show');if(!openTabs.includes(path))openTabs.push(path);renderTabs();document.querySelectorAll('.tree-file').forEach(b=>b.classList.toggle('active',b.dataset.path===path));updateEditorMeta();renderGutter()}
function renderTabs(){const el=$('editorTabs');el.innerHTML='';openTabs.forEach(p=>{const t=document.createElement('button');t.className='tab'+(p===activePath?' active':'');t.innerHTML=`${esc(p.split('/').pop())}${p===activePath&&dirty?'<span>•</span>':''}<span class="tab-close">×</span>`;t.onclick=e=>{if(e.target.classList.contains('tab-close')){openTabs=openTabs.filter(x=>x!==p);if(activePath===p&&openTabs.length)selectFile(openTabs[openTabs.length-1]);renderTabs()}else selectFile(p)};el.appendChild(t)})}
async function saveFile(){if(!activePath)return;const b=$('saveBtn');b.disabled=true;b.textContent='Saving…';try{await api('/api/workspace/file',{method:'POST',body:JSON.stringify({path:activePath,content:$('codeArea').value})});dirty=false;$('editorStatus').textContent='Saved';renderTabs()}catch(e){$('editorStatus').textContent=`Save failed: ${e.message}`;dirty=true;b.disabled=false}b.textContent='Lưu';if(!dirty)b.disabled=true}
function renderGutter(){const n=Math.max(1,$('codeArea').value.split('\n').length);$('gutter').innerHTML=Array.from({length:n},(_,i)=>`<div>${i+1}</div>`).join('')}
function updateCursor(){const ta=$('codeArea'),before=ta.value.slice(0,ta.selectionStart),line=before.split('\n').length,col=before.length-(before.lastIndexOf('\n')+1)+1;$('cursorStatus').textContent=`Ln ${line}, Col ${col}`}
function updateEditorMeta(){const p=activePath||'',ext=p.split('.').pop().toLowerCase(),map={js:'JavaScript',ts:'TypeScript',tsx:'TypeScript React',jsx:'JavaScript React',json:'JSON',html:'HTML',css:'CSS',md:'Markdown',py:'Python',yml:'YAML',yaml:'YAML',sh:'Shell'};$('languageStatus').textContent=map[ext]||'Plain Text';$('editorStatus').textContent=dirty?'Modified':'Ready';updateCursor();renderTabs()}
function setupChat(){const input=$('chatInput');$('sendBtn').onclick=send;input.oninput=()=>{$('sendBtn').disabled=!input.value.trim()};input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};$('clearChatBtn').onclick=()=>{$('chatMessages').innerHTML=''};(DATA?.chat?.initialMessages||[]).forEach(m=>appendMessage(m.role,m.text))}
async function send(){const input=$('chatInput'),text=input.value.trim();if(!text)return;appendMessage('user',text);input.value='';$('sendBtn').disabled=true;appendMessage('agent','Velclaw đang xử lý…','typing');try{const r=await api('/api/agent/chat',{method:'POST',body:JSON.stringify({message:text,path:activePath,model:DATA?.dashboard?.models?.[0]})});document.querySelectorAll('.typing').forEach(e=>e.remove());const p=r.data||r,a=p.assistant;const answer=typeof a==='string'?a:a?.text||a?.content||p.response||p.message||p.output||(r.configured===false?'Agent chưa được cấu hình.':JSON.stringify(p,null,2));appendMessage('agent',answer)}catch(e){document.querySelectorAll('.typing').forEach(x=>x.remove());appendMessage('agent',`Lỗi agent: ${e.message}`)} }
function appendMessage(role,text,cls=''){const row=document.createElement('div');row.className=`msg-row ${role} ${cls}`;const av=document.createElement('div');av.className='avatar';av.textContent=role==='user'?'U':ICON.bot;const b=document.createElement('div');b.className=`bubble ${role}`;b.textContent=text;row.append(av,b);$('chatMessages').appendChild(row);$('chatMessages').scrollTop=$('chatMessages').scrollHeight}
function setupDashboard(){$('refreshBtn').onclick=refreshStatus}
async function refreshStatus(){try{const s=await api('/api/workspace/status'),ok=!!s.agent?.configured;$('deployStatus').textContent=ok?'Agent connected':'Workspace online · Agent not configured';$('agentStatus').textContent=ok?'● connected':'● offline';$('agentStatus').style.color=ok?'var(--teal)':'var(--muted)';$('menuBackendStatus').textContent=ok?'Backend connected':'Backend online · agent not configured';$('dashboardContent').innerHTML=`<div class="dash-card"><div class="dash-title">Runtime</div><div class="dash-row"><span>Workspace</span><b>${esc(s.workspace||'local')}</b></div><div class="dash-row"><span>Node</span><b>${esc(s.server?.node||'—')}</b></div><div class="dash-row"><span>Agent</span><b class="${ok?'ok':'muted'}">${ok?'connected':'not configured'}</b></div></div><div class="dash-card"><div class="dash-title">Endpoints</div><div class="dash-row"><span>Workspace API</span><b class="ok">ready</b></div><div class="dash-row"><span>Agent API</span><b class="${ok?'ok':'muted'}">${ok?'ready':'waiting for URL'}</b></div></div>`}catch{$('deployStatus').textContent='Backend offline';$('agentStatus').textContent='● offline';$('menuBackendStatus').textContent='Backend offline'}}
function setupGit(){}
async function refreshGit(){if(!$('gitContent'))return;try{const s=await api('/api/git/status');if(!s.configured){$('gitContent').innerHTML=`<div class="dash-card"><div class="dash-title">GitHub</div><div class="dash-row"><span>Repository</span><b>${esc(s.repo||'zskbot/eve-pages')}</b></div><div class="dash-row"><span>Branch</span><b>${esc(s.branch||'main')}</b></div><div class="dash-row"><span>Status</span><b class="muted">GITHUB_TOKEN chưa cấu hình</b></div></div>`;return}let html=`<div class="dash-card"><div class="dash-title">Source Control <button class="tool-btn" onclick="createBranchUI()">New branch</button></div><div class="dash-row"><span>Repository</span><b>${esc(s.repo)}</b></div><div class="dash-row"><span>Branch</span><b>${esc(s.branch)}</b></div><div class="dash-row"><span>HEAD</span><code>${esc(s.head||'—')}</code></div></div><div class="dash-card"><div class="dash-title">Recent commits</div>`;(s.commits||[]).forEach(c=>html+=`<div class="commit-row"><code>${esc(c.sha)}</code><span>${esc(c.message)}</span><small>${esc(c.author)}</small></div>`);html+=`</div><div class="dash-card"><div class="dash-title">Actions</div><button class="primary-action" onclick="commitCurrentFile()">Commit current file</button><button class="primary-action" onclick="createPRUI()">Create pull request</button><button class="primary-action" onclick="refreshGit()">Refresh</button></div>`;$('gitContent').innerHTML=html}catch(e){$('gitContent').innerHTML=`<div class="dash-card"><b>Git error</b><p>${esc(e.message)}</p></div>`}}
async function createBranchUI(){const name=prompt('Tên branch mới');if(!name)return;try{await api('/api/git/branch',{method:'POST',body:JSON.stringify({name})});alert('Branch đã tạo: '+name);refreshGit()}catch(e){alert(e.message)}}
async function commitCurrentFile(){if(!activePath){alert('Chưa mở file');return}const message=prompt('Commit message','chore(workspace): update '+activePath);if(!message)return;try{const r=await api('/api/git/commit',{method:'POST',body:JSON.stringify({message,files:[{path:activePath,content:$('codeArea').value}]})});dirty=false;renderTabs();alert('Committed '+r.sha.slice(0,7));refreshGit()}catch(e){alert(e.message)}}
async function createPRUI(){const head=prompt('Branch chứa thay đổi');if(!head)return;const title=prompt('PR title','Velclaw Workspace changes');if(!title)return;try{const r=await api('/api/git/pr',{method:'POST',body:JSON.stringify({head,title,body:'Created from Velclaw Workspace'})});alert('PR #'+r.number+' đã tạo')}catch(e){alert(e.message)}}
function setupCommands(){const open=()=>{$('commandOverlay').classList.add('open');$('commandInput').value='';renderCommands('')},close=()=>$('commandOverlay').classList.remove('open');$('commandBtn').onclick=open;$('commandMenuBtn').onclick=()=>{ $('menuOverlay').classList.remove('open');open()};$('commandBackdrop').onclick=close;$('commandInput').oninput=e=>renderCommands(e.target.value.toLowerCase());document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open()}if(e.key==='Escape'){close();$('menuOverlay').classList.remove('open');$('treeOverlay').classList.remove('open')}})}
function renderCommands(q){const items=[['Open Codebase','files'],['Open Agent','chat'],['Open Source Control','git'],['Open Dashboard','dashboard'],['Open New Application','new-application'],['Open Agent Builder','agent-builder'],['Open Templates','templates'],['Open Plugins','marketplace'],['Open System Utilities','system'],['Open Settings','profile'],['Open file tree','tree'],['Refresh workspace','refresh']].filter(x=>x[0].toLowerCase().includes(q));$('commandList').innerHTML='';items.forEach(([label,act])=>{const b=document.createElement('div');b.className='command-row';b.innerHTML=`<div><b>${label}</b><small>${act}</small></div>`;b.onclick=()=>{if(act==='tree')$('treeOverlay').classList.add('open');else if(act==='refresh'){refreshTree();refreshStatus();refreshGit()}else if(['files','chat','git','dashboard'].includes(act))switchTab(act);else openPortal(act);$('commandOverlay').classList.remove('open')};$('commandList').appendChild(b)})}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
init();