(()=>{
const sections=[
['NEW',[['new-application','＋','New Application','Create a complete app'],['new-project','◇','New Project','Start a project workspace'],['new-agent','◌','New Agent','Create an autonomous agent'],['new-plugin','⊞','New Plugin','Create a tool integration'],['new-workspace','□','New Workspace','Isolated development space']]],
['BUILD',[['agent-builder','◈','Agent Builder','Plan · execute · review'],['chat-builder','☷','Chat Builder','Build an AI chatbot'],['app-builder','▣','App Builder','Generate application structure'],['code-generator','</>','Code Generator','Generate implementation'],['ui-builder','◫','UI Builder','Compose interface screens'],['api-builder','⇄','API Builder','Design endpoints and contracts']]],
['WORKSPACE',[['files','⌘','Codebase','Files · editor · search','tab'],['chat','◌','Agent','Chat · review · commands','tab'],['git','⑂','Source Control','Branch · commit · PR','tab'],['terminal','›_','Terminal','Shell and runtime'],['dashboard','▦','Dashboard','Runtime · services','tab']]],
['PROJECTS',[['my-projects','▤','My Projects','All workspaces'],['recent','◷','Recent','Recently opened'],['templates','▧','Templates','Ready-to-build starters'],['examples','◇','Examples','Reference projects']]],
['DESIGN & UX',[['figma','F','Figma','UI design · prototypes','external','https://www.figma.com'],['mobbin','M','Mobbin','UI/UX patterns · references','external','https://mobbin.com'],['ui-patterns','⌗','UI Patterns','Reusable interface patterns'],['components','◫','Components','Reusable building blocks'],['design-system','◈','Design System','Tokens · components · rules']]],
['LANGUAGES & SDK',[['languages','λ','Languages','Language runtimes and tooling'],['sdks','SDK','SDKs','Platform SDKs'],['packages','pkg','Packages','Dependencies'],['libraries','lib','Libraries','Reusable libraries']]],
['PLUGINS',[['installed-plugins','●','Installed','Manage installed plugins'],['marketplace','⌘','Marketplace','Discover plugins'],['mcp','MCP','MCP Servers','Tool and data connections'],['add-plugin','＋','Add Plugin','Install from a source']]],
['INTEGRATIONS',[['github','GH','GitHub','Code · issues · pull requests'],['figma-integration','F','Figma','Design context · Code Connect'],['supabase','S','Supabase','Postgres · Auth · Storage'],['vercel','V','Vercel','Deploy · preview · runtime'],['notion','N','Notion','Docs · knowledge · tasks'],['linear','L','Linear','Issues · projects'],['slack','S','Slack','Team communication'],['sentry','S','Sentry','Errors · debugging'],['posthog','P','PostHog','Analytics · feature flags']]],
['RESOURCES',[['documentation','?','Documentation','Developer references'],['apis','API','APIs','API catalog and contracts'],['resource-libraries','lib','Libraries','Library discovery'],['resource-components','◫','Components','Component references'],['models','AI','AI Models','Models and providers']]],
['TOOLS',[['command-palette','⌘','Command Palette','Navigate quickly'],['search','⌕','Search','Search workspace resources'],['diagnostics','!','Diagnostics','Health and troubleshooting']]],
['SETTINGS',[['profile','U','User Profile','Identity and preferences'],['security','⌾','Security','Tokens · keys · permissions'],['ai-settings','AI','AI & Agents','Providers · models · agent rules'],['integration-settings','↔','Integrations','Connections and OAuth'],['plugin-settings','⊞','Plugins','Permissions and MCP'],['system','⚙','System Utilities','Runtime · shell · packages'],['editor-settings','A','Editor','Theme · font · keybindings'],['workspace-settings','□','Workspace','Storage · autosave · permissions'],['notifications','●','Notifications','Agent · CI · deploy alerts'],['advanced','…','Advanced','Logs · diagnostics · reset']]]];
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function makeMenu(){if(document.getElementById('menuOverlay'))return;const o=document.createElement('aside');o.className='menu-overlay';o.id='menuOverlay';o.setAttribute('aria-hidden','true');o.innerHTML='<button class="menu-backdrop" id="menuBackdrop" aria-label="Đóng menu"></button><nav class="side-menu"><div class="menu-head"><div class="brand"><span class="brand-mark">V</span><span>Velclaw</span></div><button class="icon-btn" id="closeMenuBtn" aria-label="Đóng">×</button></div><div class="menu-scroll">'+sections.map(([title,items])=>'<div class="menu-label">'+title+'</div>'+items.map(x=>{const [id,icon,name,desc,type,url]=x;if(type==='external')return '<a class="menu-item external" href="'+url+'" target="_blank" rel="noopener"><span class="menu-icon">'+icon+'</span><span><b>'+name+'</b><small>'+desc+'</small></span><span>↗</span></a>';return '<button class="menu-item '+(type==='tab'?'':'')+'" '+(type==='tab'?'data-tab="'+id+'"':'data-view="'+id+'"')+'><span class="menu-icon">'+icon+'</span><span><b>'+name+'</b><small>'+desc+'</small></span></button>'}).join('')).join('')+'</div><div class="menu-foot"><span class="status-dot"></span><span id="menuBackendStatus">Backend checking…</span></div></nav></aside>';document.body.appendChild(o)}
function makeTree(){if(document.getElementById('treeOverlay'))return;const o=document.createElement('div');o.className='tree-overlay';o.id='treeOverlay';o.setAttribute('aria-hidden','true');o.innerHTML='<button class="menu-backdrop" id="treeBackdrop"></button><aside class="tree-drawer"><div class="drawer-head"><strong>Codebase</strong><button class="icon-btn" id="closeTreeBtn">×</button></div><div class="tree-tools"><input id="fileFilter" placeholder="Filter files…"><button id="refreshTreeBtn">↻</button></div><ul class="tree" id="fileTree"></ul></aside></div>';document.body.appendChild(o)}
makeMenu();makeTree();
document.addEventListener('click',e=>{const b=e.target.closest('.starter-card');if(b){const p=document.getElementById('builderPrompt');if(p){p.value=b.dataset.prompt||b.dataset.starter||'';p.focus()}}const send=e.target.closest('#builderSendBtn');if(send){const p=document.getElementById('builderPrompt'),chat=document.getElementById('chatInput'),go=document.getElementById('sendBtn');if(p&&chat&&go){chat.value=p.value;chat.dispatchEvent(new Event('input',{bubbles:true}));go.click()}}});
})();
